/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.loggedin;

import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.loggedin.transactions.PayBillView;
import view.loggedin.transactions.TransferView;

/**
 *
 * @author Jaison Robson Gusava
 */
public class AccountView extends javax.swing.JFrame {
    
    PayBillView payBillView;
    TransferView transferView;
    /**
     * Creates new form AccountView
     */
    public AccountView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        transactionsMenu = new javax.swing.JMenu();
        payBillMenuItem = new javax.swing.JMenuItem();
        transferMenuItem = new javax.swing.JMenuItem();
        servicesMenu = new javax.swing.JMenu();
        loanMenuItem = new javax.swing.JMenuItem();
        savingsMenuItem = new javax.swing.JMenuItem();
        accountMenu = new javax.swing.JMenu();
        extractMenuItem = new javax.swing.JMenuItem();
        manageAccountMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        transactionsMenu.setMnemonic('f');
        transactionsMenu.setText("Transações");

        payBillMenuItem.setMnemonic('o');
        payBillMenuItem.setText("Pagar Conta");
        payBillMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBillMenuItemActionPerformed(evt);
            }
        });
        transactionsMenu.add(payBillMenuItem);

        transferMenuItem.setMnemonic('s');
        transferMenuItem.setText("Transferência");
        transferMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferMenuItemActionPerformed(evt);
            }
        });
        transactionsMenu.add(transferMenuItem);

        menuBar.add(transactionsMenu);

        servicesMenu.setMnemonic('e');
        servicesMenu.setText("Serviços");

        loanMenuItem.setMnemonic('t');
        loanMenuItem.setText("Empréstimos");
        loanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanMenuItemActionPerformed(evt);
            }
        });
        servicesMenu.add(loanMenuItem);

        savingsMenuItem.setMnemonic('y');
        savingsMenuItem.setText("Poupança");
        servicesMenu.add(savingsMenuItem);

        menuBar.add(servicesMenu);

        accountMenu.setMnemonic('h');
        accountMenu.setText("Conta");

        extractMenuItem.setText("Extrato");
        accountMenu.add(extractMenuItem);

        manageAccountMenuItem.setMnemonic('c');
        manageAccountMenuItem.setText("Alterar Informações");
        accountMenu.add(manageAccountMenuItem);

        exitMenuItem.setMnemonic('a');
        exitMenuItem.setText("Sair");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        accountMenu.add(exitMenuItem);

        menuBar.add(accountMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanMenuItemActionPerformed

    private void payBillMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBillMenuItemActionPerformed
        // TODO add your handling code here:
        if (payBillView == null) {
            payBillView = new PayBillView();
            this.desktopPane.add(payBillView);
        }
        
        
        try {
            payBillView.setVisible(true);
            payBillView.setMaximum(true);
            payBillView.setSelected(true);
            payBillView.moveToFront();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AccountView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_payBillMenuItemActionPerformed

    private void transferMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferMenuItemActionPerformed
        // TODO add your handling code here:
        if (transferView == null) {
            transferView = new TransferView();
            this.desktopPane.add(transferView);
        }
        
        try {
            transferView.setVisible(true);
            transferView.setMaximum(true);
            transferView.setSelected(true);
            transferView.moveToFront();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AccountView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_transferMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accountMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem extractMenuItem;
    private javax.swing.JMenuItem loanMenuItem;
    private javax.swing.JMenuItem manageAccountMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem payBillMenuItem;
    private javax.swing.JMenuItem savingsMenuItem;
    private javax.swing.JMenu servicesMenu;
    private javax.swing.JMenu transactionsMenu;
    private javax.swing.JMenuItem transferMenuItem;
    // End of variables declaration//GEN-END:variables

}
