/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.loggedout;

import com.mongodb.client.MongoClient;
import model.dao.ClienteDAO;
import model.dao.ContaDAO;
import control.Globals;
import model.domain.Banco;
import model.domain.Cliente;
import model.domain.Conta;
import mongo_client.Mongo;

/**
 *
 * @author Jaison Robson Gusava
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        jLabelCriarNumero1 = new javax.swing.JLabel();
        jTextFieldLoginNmr = new javax.swing.JTextField();
        jPasswordFieldLoginSenha = new javax.swing.JPasswordField();
        jLabelCriarSenha1 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelCriarConta = new javax.swing.JPanel();
        jLabelCriarTelefone1 = new javax.swing.JLabel();
        jLabelCriarRG2 = new javax.swing.JLabel();
        jTextFieldCriarRG1 = new javax.swing.JTextField();
        jLabelCriarRG3 = new javax.swing.JLabel();
        jFormattedTextFieldDataNascimento1 = new javax.swing.JFormattedTextField();
        jLabelCriarNumero2 = new javax.swing.JLabel();
        jLabelCriarSenha2 = new javax.swing.JLabel();
        jLabelBanco1 = new javax.swing.JLabel();
        jTextFieldCriarNmr1 = new javax.swing.JTextField();
        jComboBoxBanco1 = new javax.swing.JComboBox<>();
        jPasswordFieldCriarSenha1 = new javax.swing.JPasswordField();
        jButtonCriarConta1 = new javax.swing.JButton();
        jTextFieldCriarNome1 = new javax.swing.JTextField();
        jLabelCriarCliente1 = new javax.swing.JLabel();
        jTextFieldCriarCPF1 = new javax.swing.JTextField();
        jLabelCriarCPF1 = new javax.swing.JLabel();
        jLabelCriarEstado1 = new javax.swing.JLabel();
        jTextFieldCriarEstado1 = new javax.swing.JTextField();
        jLabelCriarCidade1 = new javax.swing.JLabel();
        jTextFieldCriarCidade1 = new javax.swing.JTextField();
        jTextFieldCriarPais1 = new javax.swing.JTextField();
        jLabelCriarPais1 = new javax.swing.JLabel();
        jTextFieldCriarTelefone1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabelCriarNumero1.setText("Numero");

        jLabelCriarSenha1.setText("Senha");

        jButtonLogin.setText("Acessar");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCriarNumero1)
                    .addComponent(jLabelCriarSenha1))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextFieldLoginNmr)
                    .addComponent(jPasswordFieldLoginSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(789, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarNumero1)
                    .addComponent(jTextFieldLoginNmr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarSenha1)
                    .addComponent(jPasswordFieldLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButtonLogin)
                .addContainerGap(643, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acessar", loginPanel);

        jLabelCriarTelefone1.setText("Telefone");

        jLabelCriarRG2.setText("RG");

        jTextFieldCriarRG1.setPreferredSize(new java.awt.Dimension(500, 20));

        jLabelCriarRG3.setText("Data nascimento (31/12/2019)");

        jFormattedTextFieldDataNascimento1.setColumns(2);
        jFormattedTextFieldDataNascimento1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldDataNascimento1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldDataNascimento1.setName(""); // NOI18N
        jFormattedTextFieldDataNascimento1.setPreferredSize(new java.awt.Dimension(500, 20));

        jLabelCriarNumero2.setText("Numero da conta");

        jLabelCriarSenha2.setText("Senha");

        jLabelBanco1.setText("Banco");

        jTextFieldCriarNmr1.setPreferredSize(new java.awt.Dimension(30, 20));

        jComboBoxBanco1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBoxBanco1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPasswordFieldCriarSenha1.setPreferredSize(new java.awt.Dimension(30, 20));

        jButtonCriarConta1.setText("Criar");
        jButtonCriarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarConta1ActionPerformed(evt);
            }
        });

        jTextFieldCriarNome1.setPreferredSize(new java.awt.Dimension(500, 20));

        jLabelCriarCliente1.setText("Nome");

        jTextFieldCriarCPF1.setPreferredSize(new java.awt.Dimension(500, 20));

        jLabelCriarCPF1.setText("CPF");

        jLabelCriarEstado1.setText("Estado");

        jTextFieldCriarEstado1.setPreferredSize(new java.awt.Dimension(500, 20));

        jLabelCriarCidade1.setText("Cidade");

        jTextFieldCriarCidade1.setPreferredSize(new java.awt.Dimension(500, 20));

        jTextFieldCriarPais1.setPreferredSize(new java.awt.Dimension(500, 20));

        jLabelCriarPais1.setText("Pais");

        jTextFieldCriarTelefone1.setPreferredSize(new java.awt.Dimension(500, 20));

        javax.swing.GroupLayout jPanelCriarContaLayout = new javax.swing.GroupLayout(jPanelCriarConta);
        jPanelCriarConta.setLayout(jPanelCriarContaLayout);
        jPanelCriarContaLayout.setHorizontalGroup(
            jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCriarContaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCriarContaLayout.createSequentialGroup()
                        .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCriarCliente1)
                            .addComponent(jLabelCriarCPF1)
                            .addComponent(jLabelCriarEstado1)
                            .addComponent(jLabelCriarCidade1)
                            .addComponent(jLabelCriarPais1)
                            .addComponent(jLabelCriarTelefone1)
                            .addComponent(jLabelCriarRG2)
                            .addComponent(jLabelCriarRG3))
                        .addGap(85, 85, 85)
                        .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCriarNome1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                            .addComponent(jTextFieldCriarCPF1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCriarEstado1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCriarCidade1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCriarPais1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCriarTelefone1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCriarRG1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldDataNascimento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelCriarContaLayout.createSequentialGroup()
                        .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCriarSenha2)
                            .addComponent(jLabelCriarNumero2)
                            .addComponent(jLabelBanco1))
                        .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCriarContaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCriarConta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelCriarContaLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxBanco1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCriarNmr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPasswordFieldCriarSenha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(109, 109, 109))
        );
        jPanelCriarContaLayout.setVerticalGroup(
            jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCriarContaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarCliente1)
                    .addComponent(jTextFieldCriarNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarCPF1)
                    .addComponent(jTextFieldCriarCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarEstado1)
                    .addComponent(jTextFieldCriarEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarCidade1)
                    .addComponent(jTextFieldCriarCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarPais1)
                    .addComponent(jTextFieldCriarPais1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarTelefone1)
                    .addComponent(jTextFieldCriarTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarRG2)
                    .addComponent(jTextFieldCriarRG1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarRG3)
                    .addComponent(jFormattedTextFieldDataNascimento1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBanco1)
                    .addComponent(jComboBoxBanco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarNumero2)
                    .addComponent(jTextFieldCriarNmr1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCriarSenha2)
                    .addComponent(jPasswordFieldCriarSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonCriarConta1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanelCriarConta);
        jPanelCriarConta.getAccessibleContext().setAccessibleName("JPanelCriarContaName");
        jPanelCriarConta.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Criar Conta", jScrollPane1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Bancário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("f");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBanco1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBoxBanco1AncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxBanco1AncestorAdded

    private void jButtonCriarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarConta1ActionPerformed
        // TODO add your handling code here:
        
        ClienteDAO clientedao = new ClienteDAO();        
        Cliente cliente = new Cliente();
        cliente.setNome(jTextFieldCriarNome1.getText());
        cliente.setCpf(Long.parseLong(jTextFieldCriarCPF1.getText()));
        cliente.setEstado(jTextFieldCriarEstado1.getText());
        cliente.setCidade(jTextFieldCriarCidade1.getText());
        cliente.setPais(jTextFieldCriarPais1.getText());
        cliente.setTelefone(Integer.parseInt(jTextFieldCriarTelefone1.getText()));
        cliente.setRg(Integer.parseInt(jTextFieldCriarRG1.getText()));
        cliente.setNascimento(jFormattedTextFieldDataNascimento1.getText());
        
        Boolean criouCliente = clientedao.criar(cliente);
        
        System.out.println(cliente.getCpf());
        
        clientedao.requestCliente(cliente.getCpf());
        
        if (criouCliente) {
            ContaDAO contadao = new ContaDAO();        
            Conta conta = new Conta();

            Banco b = (Banco)jComboBoxBanco1.getSelectedItem();

            conta.setBancoId(b.getId());
            conta.setSenha(jPasswordFieldCriarSenha1.getPassword().toString());
            conta.setClienteId(cliente.getId());
            conta.setNumero(Integer.parseInt(jTextFieldCriarNmr1.getText()));
        }
    }//GEN-LAST:event_jButtonCriarConta1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        MongoClient client = Mongo.getInstance();
        
        client.close();
        Globals.comment("Fechou mongo client");
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public void showWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriarConta1;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JComboBox<String> jComboBoxBanco1;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBanco1;
    private javax.swing.JLabel jLabelCriarCPF1;
    private javax.swing.JLabel jLabelCriarCidade1;
    private javax.swing.JLabel jLabelCriarCliente1;
    private javax.swing.JLabel jLabelCriarEstado1;
    private javax.swing.JLabel jLabelCriarNumero1;
    private javax.swing.JLabel jLabelCriarNumero2;
    private javax.swing.JLabel jLabelCriarPais1;
    private javax.swing.JLabel jLabelCriarRG2;
    private javax.swing.JLabel jLabelCriarRG3;
    private javax.swing.JLabel jLabelCriarSenha1;
    private javax.swing.JLabel jLabelCriarSenha2;
    private javax.swing.JLabel jLabelCriarTelefone1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCriarConta;
    private javax.swing.JPasswordField jPasswordFieldCriarSenha1;
    private javax.swing.JPasswordField jPasswordFieldLoginSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldCriarCPF1;
    private javax.swing.JTextField jTextFieldCriarCidade1;
    private javax.swing.JTextField jTextFieldCriarEstado1;
    private javax.swing.JTextField jTextFieldCriarNmr1;
    private javax.swing.JTextField jTextFieldCriarNome1;
    private javax.swing.JTextField jTextFieldCriarPais1;
    private javax.swing.JTextField jTextFieldCriarRG1;
    private javax.swing.JTextField jTextFieldCriarTelefone1;
    private javax.swing.JTextField jTextFieldLoginNmr;
    private javax.swing.JPanel loginPanel;
    // End of variables declaration//GEN-END:variables
}
